version: '3.8'

services:
  guardian-mcp:
    image: guardian-orchestrator-mcp:latest
    container_name: guardian-mcp
    build:
      context: ./claude-flow-diego/claude-diego-flow
      dockerfile: docker/Dockerfile.guardian-mcp
    environment:
      # Configurações principais
      - NODE_ENV=production
      - PROJECT_ROOT=/workspace
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # MCP Bridge
      - MCP_BRIDGE_URL=http://mem0-bridge:3002
      
      # API REST
      - GUARDIAN_API_PORT=3004
      
      # Memória
      - GUARDIAN_MEMORY_USER=guardian-orchestrator
      - AUTO_SAVE_INTERVAL=30000
      
      # GitHub (opcional)
      - GITHUB_OWNER=${GITHUB_OWNER:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      
      # Puppeteer (para screenshots)
      - PUPPETEER_URL=http://browserless:3000
    
    volumes:
      # Workspace
      - .:/workspace:ro
      
      # Reports e logs persistentes
      - guardian-reports:/app/reports
      - guardian-logs:/app/logs
      
      # Memória local (backup)
      - guardian-memory:/app/memory
      
      # Docker socket (para gerenciar containers)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    networks:
      - claude-network
    
    ports:
      - "3004:3004"  # API REST
    
    depends_on:
      - mem0-bridge
    
    restart: unless-stopped
    
    labels:
      - "com.thecryptofrontier.service=guardian-mcp"
      - "com.thecryptofrontier.type=orchestrator"
      - "com.thecryptofrontier.version=2.0.0"
    
    # Limites de recursos
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Mem0 Bridge (necessário para memória persistente)
  mem0-bridge:
    image: mem0-bridge:latest
    container_name: mem0-bridge
    build:
      context: ./claude-flow-diego/mem0-bridge
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MEM0_API_KEY=${MEM0_API_KEY:-}
      - MEM0_ORG_ID=${MEM0_ORG_ID:-}
      - MEMORY_DIR=/data
    volumes:
      - mem0-data:/data
    networks:
      - claude-network
    ports:
      - "3002:3002"
    restart: unless-stopped

  # Browserless (para screenshots)
  browserless:
    image: browserless/chrome:latest
    container_name: browserless
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=10
      - MAX_QUEUE_LENGTH=20
    networks:
      - claude-network
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  guardian-reports:
    name: guardian-mcp-reports
  guardian-logs:
    name: guardian-mcp-logs
  guardian-memory:
    name: guardian-mcp-memory
  mem0-data:
    name: mem0-bridge-data

networks:
  claude-network:
    external: true