version: '3.7'

services:
  # Serviço Proxy Caddy com descoberta automática
  caddy-proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 9080:80
      - 9444:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    networks:
      - caddy
    restart: unless-stopped
    secrets:
      - caddy_api_token

  # Serviço The Crypto Frontier (tenant1)
  tenant1-frontier:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - /home/sanity/thecryptofrontier:/app
    command: npm run dev -- -p 3200
    networks:
      - caddy
    ports:
      - "3200:3200"
    labels:
      caddy: "tenant1.localhost thecryptofrontier.agentesintegrados.com"
      caddy.reverse_proxy: "{{upstreams 3200}}"
    secrets:
      - frontier_api_key
      - db_password

networks:
  caddy:
    external: true

volumes:
  caddy_data:

# Definição dos secrets
secrets:
  caddy_api_token:
    file: ./secrets/caddy_api_token.txt  # Caminho para o arquivo que contém o segredo
  frontier_api_key:
    file: ./secrets/frontier_api_key.txt
  db_password:
    file: ./secrets/db_password.txt 