version: '3.8'

services:
  cleanup-specialist:
    image: cleanup-specialist:latest
    container_name: cleanup-specialist
    build:
      context: ./claude-flow-diego/claude-diego-flow
      dockerfile: docker/Dockerfile.cleanup-specialist-simple
      args:
        - NODE_VERSION=20-alpine
    environment:
      # Configurações principais
      - NODE_ENV=production
      - PROJECT_ROOT=/workspace
      - ARCHIVE_DIR=/workspace/archived-tests
      
      # Opções de execução
      - DRY_RUN=${DRY_RUN:-true}
      - AGGRESSIVE=${AGGRESSIVE:-false}
      - INCLUDE_NODE_MODULES=${INCLUDE_NODE_MODULES:-false}
      - INCLUDE_TESTS=${INCLUDE_TESTS:-false}
      
      # Limites
      - MAX_FILE_SIZE=50MB
      - SCAN_TIMEOUT=300s
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=json
      
      # Integração com Guardian
      - GUARDIAN_URL=http://unified-guardian:3003
      - REPORT_TO_GUARDIAN=${REPORT_TO_GUARDIAN:-true}
    
    volumes:
      # Workspace - read-only por padrão
      - ${WORKSPACE_PATH:-.}:/workspace:${MOUNT_MODE:-ro}
      
      # Reports persistentes
      - cleanup-reports:/app/reports
      
      # Logs
      - cleanup-logs:/app/logs
      
      # Cache para performance
      - cleanup-cache:/app/.cache
    
    networks:
      - claude-network
    
    # Limites de recursos
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Não reinicia automaticamente
    restart: "no"
    
    # Profile para execução sob demanda
    profiles:
      - cleanup
    
    # Labels para organização
    labels:
      - "com.thecryptofrontier.service=cleanup-specialist"
      - "com.thecryptofrontier.type=ephemeral"
      - "com.thecryptofrontier.version=1.0.0"
    
    # Comando padrão (análise)
    command: ["npm", "run", "cleanup:analyze"]

  # Opcional: Cleanup Scheduler (cron job containerizado)
  cleanup-scheduler:
    image: cleanup-specialist:latest
    container_name: cleanup-scheduler
    environment:
      - SCHEDULE=0 2 * * *  # Diariamente às 2AM
      - DRY_RUN=true
      - GUARDIAN_URL=http://unified-guardian:3003
    volumes:
      - .:/workspace:ro
      - cleanup-reports:/app/reports
      - cleanup-logs:/app/logs
    networks:
      - claude-network
    profiles:
      - cleanup-scheduled
    command: ["npm", "run", "cleanup:scheduler"]
    restart: unless-stopped

volumes:
  cleanup-reports:
    name: cleanup-specialist-reports
  cleanup-logs:
    name: cleanup-specialist-logs
  cleanup-cache:
    name: cleanup-specialist-cache

networks:
  claude-network:
    external: true