version: '3.8'

services:
  # Frontend Next.js
  thecryptofrontier:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: thecryptofrontier-app
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SANITY_PROJECT_ID=brby2yrg
      - NEXT_PUBLIC_SANITY_DATASET=production
      - NEXT_PUBLIC_SANITY_API_VERSION=2023-05-03
      - TZ=America/Sao_Paulo
      # Algolia
      - NEXT_PUBLIC_ALGOLIA_APP_ID=42TZWHW8UP
      - NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=b32edbeb383fc3d1279658e7c3661843
      - NEXT_PUBLIC_ALGOLIA_INDEX_NAME=development_mcpx_content
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

networks:
  app-network:
    driver: bridge

# Para desenvolvimento (opcional)
# Descomente as linhas abaixo se quiser rodar em modo desenvolvimento
#  thecryptofrontier-dev:
#    build:
#      context: .
#      dockerfile: Dockerfile.nextjs
#      target: builder
#    container_name: thecryptofrontier-dev
#    ports:
#      - "3002:3000"
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./src:/app/src
#      - ./package.json:/app/package.json
#    command: npm run dev
#    networks:
#      - app-network 