version: '3.8'

services:
  # Mem0 Vector Database (Qdrant)
  mem0-qdrant:
    image: qdrant/qdrant:latest
    container_name: mem0-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /var/lib/docker/volumes/thecryptofrontier-data/_data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - mem0-network
    restart: unless-stopped

  # Redis for caching
  mem0-redis:
    image: redis:7-alpine
    container_name: mem0-redis
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/docker/volumes/thecryptofrontier-data/_data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - mem0-network
    restart: unless-stopped

  # PostgreSQL for metadata storage
  mem0-postgres:
    image: postgres:15-alpine
    container_name: mem0-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mem0
      POSTGRES_PASSWORD: mem0password
      POSTGRES_DB: mem0db
    volumes:
      - /var/lib/docker/volumes/thecryptofrontier-data/_data/postgres:/var/lib/postgresql/data
    networks:
      - mem0-network
    restart: unless-stopped

  # Mem0 API Service
  mem0-api:
    build:
      context: ./mem0
      dockerfile: Dockerfile
    container_name: mem0-api
    ports:
      - "8000:8000"
    environment:
      # Database connections
      QDRANT_URL: http://mem0-qdrant:6333
      REDIS_URL: redis://mem0-redis:6379
      DATABASE_URL: postgresql://mem0:mem0password@mem0-postgres:5432/mem0db
      
      # API Configuration
      MEM0_API_KEY: ${MEM0_API_KEY:-your-secure-api-key}
      NODE_ENV: production
      
      # Documentation site URL (para scraping)
      DOCS_URL: https://docs.mem0.ai
      
      # OpenAI Configuration (opcional)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      
      # Embedding model
      EMBEDDING_MODEL: text-embedding-3-small
    depends_on:
      - mem0-qdrant
      - mem0-redis
      - mem0-postgres
    volumes:
      - ./mem0/src:/app/src
      - ./mem0/docs-cache:/app/docs-cache
    networks:
      - mem0-network
    restart: unless-stopped

  # Documentation Scraper Service
  mem0-docs-scraper:
    build:
      context: ./mem0
      dockerfile: Dockerfile.scraper
    container_name: mem0-docs-scraper
    environment:
      DOCS_URL: https://docs.mem0.ai
      CACHE_DIR: /app/docs-cache
      UPDATE_INTERVAL: 3600 # Update every hour
      DATABASE_URL: postgresql://mem0:mem0password@mem0-postgres:5432/mem0db
      QDRANT_URL: http://mem0-qdrant:6333
    depends_on:
      - mem0-postgres
      - mem0-qdrant
    volumes:
      - ./mem0/docs-cache:/app/docs-cache
    networks:
      - mem0-network
    restart: unless-stopped

  # Web UI para visualização (opcional)
  mem0-ui:
    build:
      context: ./mem0
      dockerfile: Dockerfile.ui
    container_name: mem0-ui
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_DOCS_URL: https://docs.mem0.ai
    depends_on:
      - mem0-api
    networks:
      - mem0-network
    restart: unless-stopped

networks:
  mem0-network:
    driver: bridge

volumes:
  qdrant-storage:
  redis-data:
  postgres-data:
  docs-cache: