version: '3.8'

services:
  # Serviço Streamlit para interface de usuário
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-crewai-ui
    # Removemos a porta exposta, agora acessamos via Caddy
    expose:
      - "8501"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SANITY_PROJECT_ID=${SANITY_PROJECT_ID}
      - SANITY_API_TOKEN=${SANITY_API_TOKEN}
      - NEXT_PUBLIC_ALGOLIA_APP_ID=${NEXT_PUBLIC_ALGOLIA_APP_ID}
      - NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY}
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - crewai-network
    
  # Serviço Redis para cache e filas
  redis:
    image: redis:alpine
    container_name: redis-crewai-cache
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - crewai-network
  
  # Proxy reverso Caddy
  caddy:
    image: caddy:2
    container_name: caddy-crewai-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"  # Exposição na porta 8080 conforme Caddyfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/app/static
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - crewai-network
    depends_on:
      - streamlit

volumes:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  crewai-network:
    driver: bridge