version: '3.8'

services:
  # Serviço Streamlit para interface de usuário
  streamlit:
    build: .
    container_name: streamlit-crewai-ui
    ports:
      - "8501:8501"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SANITY_PROJECT_ID=${SANITY_PROJECT_ID}
      - SANITY_API_TOKEN=${SANITY_API_TOKEN}
      - NEXT_PUBLIC_ALGOLIA_APP_ID=${NEXT_PUBLIC_ALGOLIA_APP_ID}
      - NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY}
    volumes:
      - ./posts_para_traduzir:/app/posts_para_traduzir
      - ./posts_traduzidos:/app/posts_traduzidos
      - ./posts_formatados:/app/posts_formatados
      - ./posts_publicados:/app/posts_publicados
      - ./output:/app/output
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - crewai-network
    command: ["streamlit", "run", "app_modular.py", "--server.port=8501", "--server.address=0.0.0.0"]
    
  # Serviço Redis para cache e filas
  redis:
    image: redis:alpine
    container_name: redis-crewai-cache
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - crewai-network

volumes:
  redis_data:

networks:
  crewai-network:
    driver: bridge