# Configuração das tarefas para automação de RSS até Sanity
fetch_rss_task:
  description: >
    Buscar e extrair as 5 notícias mais recentes e relevantes sobre criptomoedas dos feeds RSS
    especificados: {rss_feeds}. Para cada notícia, extraia o título, link, data de publicação, 
    autor (se disponível) e um resumo do conteúdo.
  expected_output: >
    Uma lista estruturada com as 5 notícias mais relevantes, contendo para cada uma:
    título, link, data, autor, resumo e tags sugeridas.
  agent: rss_reader

analyze_content_task:
  description: >
    Analise profundamente cada uma das notícias extraídas. Para cada notícia:
    1. Identifique os principais pontos tecnológicos ou de mercado
    2. Determine o impacto potencial para investidores e entusiastas
    3. Relacione com tendências atuais do mercado de criptomoedas
    4. Sugira insights adicionais relevantes
  expected_output: >
    Uma análise detalhada de cada notícia, com pontos principais, impactos, contexto
    de mercado e insights adicionais.
  agent: content_analyst
  context:
    - fetch_rss_task

write_post_task:
  description: >
    Crie um artigo completo para o blog TheCryptoFrontier baseado na 
    notícia mais relevante das análises recebidas. O artigo deve:
    1. Ter um título envolvente
    2. Começar com uma introdução cativante
    3. Desenvolver os pontos principais com clareza
    4. Incluir análise de impacto e contexto
    5. Terminar com uma conclusão que amarre os pontos principais
    6. Ter entre 600-800 palavras
    7. Incluir sugestões de tags relevantes
  expected_output: >
    Um artigo completo, bem estruturado e informativo sobre criptomoedas,
    pronto para publicação, com título, corpo, conclusão e tags.
  agent: content_writer
  context:
    - analyze_content_task

format_for_sanity_task:
  description: >
    Transforme o artigo recebido em um formato compatível com o schema do Sanity CMS.
    Certifique-se de incluir todos os campos necessários:
    - slug (baseado no título)
    - title
    - content (formatado como blocos Sanity)
    - excerpt (resumo curto)
    - author
    - date (data atual)
    - tags (baseado nas sugestões)
    - categories (relacionado a criptomoedas/blockchain)
    - featuredImage (sugestão de URL de imagem relacionada)
  expected_output: >
    Um objeto JSON completo formatado de acordo com o schema do Sanity,
    contendo todos os campos necessários para publicação.
  agent: sanity_publisher
  context:
    - write_post_task
  output_file: output/sanity_post.json 